project:
  type: book

number-depth: 2

book:
  title: "Software Engineering Lecture Notes WS 24/25 "
  author: "Igor Dimitrov"
  date: "10/14/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - 01/01.qmd
    - 02/02.qmd
    - 03/03.qmd
    - 04/04.qmd
    - 05/05.qmd
    - 06/06.qmd
    - 07/07.qmd
  downloads: pdf
  

bibliography: references.bib


format:
  html:
    theme: cosmo
    toc-depth: 5
    toc-expand: 2
  pdf:
    documentclass: scrreprt
    number-depth: 4
    toc-depth: 4



